export interface Flashcard {
  id: number;
  topic: string;
  difficulty: "Easy" | "Medium" | "Hard";
  title: string;
  question: string;
  hint: string;
  approach: string;
  timeComplexity: string;
  spaceComplexity: string;
  pattern: string;
}

export const TOPICS = [
  "Arrays & Hashing",
  "Two Pointers",
  "Sliding Window",
  "Stack",
  "Binary Search",
  "Linked List",
  "Trees",
  "Tries",
  "Heap / Priority Queue",
  "Backtracking",
  "Graphs",
  "Dynamic Programming",
  "Greedy",
  "Intervals",
  "Math & Geometry",
] as const;

export type Topic = (typeof TOPICS)[number];

export const DIFFICULTY_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  Easy: { bg: "bg-emerald-500/10", text: "text-emerald-600", border: "border-emerald-500/20" },
  Medium: { bg: "bg-amber-500/10", text: "text-amber-600", border: "border-amber-500/20" },
  Hard: { bg: "bg-rose-500/10", text: "text-rose-600", border: "border-rose-500/20" },
};

export const FLASHCARDS: Flashcard[] = [
  // ── Arrays & Hashing ──────────────────────────────────
  {
    id: 1,
    topic: "Arrays & Hashing",
    difficulty: "Easy",
    title: "Two Sum",
    question: "Given an array of integers and a target, return indices of two numbers that add up to the target.",
    hint: "Use a hash map to store complements.",
    approach: "Iterate through the array. For each element, check if (target - element) exists in the hash map. If yes, return both indices. Otherwise, store the current element and its index.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    pattern: "Hash Map Lookup",
  },
  {
    id: 2,
    topic: "Arrays & Hashing",
    difficulty: "Easy",
    title: "Contains Duplicate",
    question: "Given an integer array, return true if any value appears at least twice.",
    hint: "A Set gives O(1) lookups.",
    approach: "Insert elements into a HashSet. If an element already exists in the set, return true. If you finish the loop without finding a duplicate, return false.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    pattern: "Hash Set",
  },
  {
    id: 3,
    topic: "Arrays & Hashing",
    difficulty: "Medium",
    title: "Group Anagrams",
    question: "Given an array of strings, group the anagrams together.",
    hint: "Sorted characters form a canonical key.",
    approach: "For each string, sort its characters to create a key. Use a hash map to group strings by their sorted key. Return the grouped values.",
    timeComplexity: "O(n · k log k)",
    spaceComplexity: "O(n · k)",
    pattern: "Hash Map Grouping",
  },
  {
    id: 4,
    topic: "Arrays & Hashing",
    difficulty: "Medium",
    title: "Top K Frequent Elements",
    question: "Given an integer array and k, return the k most frequent elements.",
    hint: "Bucket sort by frequency avoids n·log(n).",
    approach: "Count frequencies with a hash map, then use bucket sort: create an array where index = frequency, and elements at that index are nums with that frequency. Walk the buckets from high to low to collect k elements.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    pattern: "Bucket Sort",
  },
  {
    id: 5,
    topic: "Arrays & Hashing",
    difficulty: "Medium",
    title: "Product of Array Except Self",
    question: "Return an array where each element is the product of all other elements, without using division.",
    hint: "Use prefix and suffix product passes.",
    approach: "First pass: compute prefix products (left to right). Second pass: multiply each position by the suffix product (right to left). This gives the product of all elements except self.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1) extra",
    pattern: "Prefix / Suffix",
  },
  // ── Two Pointers ──────────────────────────────────────
  {
    id: 6,
    topic: "Two Pointers",
    difficulty: "Easy",
    title: "Valid Palindrome",
    question: "Given a string, determine if it is a palindrome considering only alphanumeric characters.",
    hint: "Use two pointers from both ends, skip non-alnum.",
    approach: "Place left pointer at start, right at end. Skip non-alphanumeric chars. Compare characters (case-insensitive). Move inward until pointers cross.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    pattern: "Two Pointers (Converging)",
  },
  {
    id: 7,
    topic: "Two Pointers",
    difficulty: "Medium",
    title: "3Sum",
    question: "Find all unique triplets in the array that sum to zero.",
    hint: "Sort + fix one element + two-pointer scan.",
    approach: "Sort the array. For each element, use two pointers on the remaining subarray to find pairs that sum to its negative. Skip duplicates to avoid repeated triplets.",
    timeComplexity: "O(n²)",
    spaceComplexity: "O(1) extra",
    pattern: "Sort + Two Pointers",
  },
  {
    id: 8,
    topic: "Two Pointers",
    difficulty: "Medium",
    title: "Container With Most Water",
    question: "Given heights, find two lines that together with the x-axis form a container holding the most water.",
    hint: "Start wide, move the shorter line inward.",
    approach: "Place pointers at both ends. Calculate area = min(height[l], height[r]) × (r - l). Move the pointer with the shorter height inward, since moving the taller one can only decrease area.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    pattern: "Greedy Two Pointers",
  },
  // ── Sliding Window ────────────────────────────────────
  {
    id: 9,
    topic: "Sliding Window",
    difficulty: "Medium",
    title: "Longest Substring Without Repeating Characters",
    question: "Find the length of the longest substring without repeating characters.",
    hint: "Expand right, shrink left when a duplicate appears.",
    approach: "Maintain a set and two pointers. Expand the right pointer; if a character is already in the set, shrink from the left until it's removed. Track the maximum window size.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(min(n, m))",
    pattern: "Variable Sliding Window",
  },
  {
    id: 10,
    topic: "Sliding Window",
    difficulty: "Hard",
    title: "Minimum Window Substring",
    question: "Find the minimum window in s that contains all characters of t.",
    hint: "Use a frequency map and shrink when valid.",
    approach: "Count character frequencies of t. Expand window by moving the right pointer. When all characters are satisfied, try to shrink from the left while maintaining validity. Track the minimum valid window.",
    timeComplexity: "O(n + m)",
    spaceComplexity: "O(m)",
    pattern: "Variable Sliding Window + Frequency Count",
  },
  {
    id: 11,
    topic: "Sliding Window",
    difficulty: "Hard",
    title: "Sliding Window Maximum",
    question: "Given an array and window size k, return the max value in each window position.",
    hint: "Use a monotonic decreasing deque.",
    approach: "Maintain a deque of indices in decreasing order of values. For each new element, remove smaller elements from the back. Remove out-of-window indices from the front. The front of the deque is the window max.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    pattern: "Monotonic Deque",
  },
  // ── Stack ─────────────────────────────────────────────
  {
    id: 12,
    topic: "Stack",
    difficulty: "Easy",
    title: "Valid Parentheses",
    question: "Given a string of brackets, determine if the input is valid (properly opened and closed).",
    hint: "Push openers, pop and match closers.",
    approach: "Use a stack. For opening brackets, push. For closing brackets, check if the stack top matches. If mismatch or stack is empty, return false. At end, stack should be empty.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    pattern: "Stack Matching",
  },
  {
    id: 13,
    topic: "Stack",
    difficulty: "Medium",
    title: "Daily Temperatures",
    question: "Given daily temperatures, return how many days until a warmer temperature for each day.",
    hint: "Monotonic decreasing stack of indices.",
    approach: "Use a stack of indices. For each temperature, while the stack has indices with lower temperatures, pop them and set their answer to (current index - popped index). Push current index.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    pattern: "Monotonic Stack",
  },
  {
    id: 14,
    topic: "Stack",
    difficulty: "Hard",
    title: "Largest Rectangle in Histogram",
    question: "Find the largest rectangular area in a histogram.",
    hint: "Stack tracks indices of increasing heights.",
    approach: "Use a stack. For each bar, while the stack top is taller, pop it and calculate the area with that height and width spanning to the current index. Handle remaining bars after the loop.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    pattern: "Monotonic Stack",
  },
  // ── Binary Search ─────────────────────────────────────
  {
    id: 15,
    topic: "Binary Search",
    difficulty: "Easy",
    title: "Binary Search",
    question: "Given a sorted array and target, return the index or -1 if not found.",
    hint: "Classic lo/hi with mid = (lo + hi) / 2.",
    approach: "Set lo = 0, hi = n-1. While lo ≤ hi, compute mid. If nums[mid] == target, return mid. If nums[mid] < target, lo = mid + 1. Else hi = mid - 1.",
    timeComplexity: "O(log n)",
    spaceComplexity: "O(1)",
    pattern: "Classic Binary Search",
  },
  {
    id: 16,
    topic: "Binary Search",
    difficulty: "Medium",
    title: "Search in Rotated Sorted Array",
    question: "Search for a target in a sorted array that has been rotated at some pivot.",
    hint: "One half is always sorted — determine which one.",
    approach: "Binary search, but at each step determine which half is sorted. If target falls within the sorted half, search there; otherwise search the other half.",
    timeComplexity: "O(log n)",
    spaceComplexity: "O(1)",
    pattern: "Modified Binary Search",
  },
  {
    id: 17,
    topic: "Binary Search",
    difficulty: "Hard",
    title: "Median of Two Sorted Arrays",
    question: "Find the median of two sorted arrays in logarithmic time.",
    hint: "Binary search on the partition of the smaller array.",
    approach: "Binary search on the shorter array to find a partition where left elements ≤ right elements across both arrays. The median comes from the boundary elements of the partition.",
    timeComplexity: "O(log(min(m, n)))",
    spaceComplexity: "O(1)",
    pattern: "Binary Search on Answer",
  },
  // ── Linked List ───────────────────────────────────────
  {
    id: 18,
    topic: "Linked List",
    difficulty: "Easy",
    title: "Reverse Linked List",
    question: "Reverse a singly linked list.",
    hint: "Track prev, curr, next and reassign pointers.",
    approach: "Initialize prev = null. For each node, save next, point current.next to prev, advance prev to current, current to saved next. Return prev.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    pattern: "Pointer Manipulation",
  },
  {
    id: 19,
    topic: "Linked List",
    difficulty: "Easy",
    title: "Linked List Cycle",
    question: "Determine if a linked list has a cycle.",
    hint: "Floyd's tortoise and hare algorithm.",
    approach: "Use slow (1 step) and fast (2 steps) pointers. If they meet, there's a cycle. If fast reaches null, there's no cycle.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    pattern: "Fast & Slow Pointers",
  },
  {
    id: 20,
    topic: "Linked List",
    difficulty: "Medium",
    title: "Merge Two Sorted Lists",
    question: "Merge two sorted linked lists into one sorted list.",
    hint: "Use a dummy head and compare nodes.",
    approach: "Create a dummy node. Compare heads of both lists, attach the smaller one, advance that pointer. After one list is exhausted, attach the remaining list.",
    timeComplexity: "O(n + m)",
    spaceComplexity: "O(1)",
    pattern: "Merge Pattern",
  },
  {
    id: 21,
    topic: "Linked List",
    difficulty: "Hard",
    title: "Merge K Sorted Lists",
    question: "Merge k sorted linked lists into one sorted list.",
    hint: "Min-heap of k list heads.",
    approach: "Insert the head of each list into a min-heap. Extract-min, add to result, and push the next node from that list. Repeat until the heap is empty.",
    timeComplexity: "O(n log k)",
    spaceComplexity: "O(k)",
    pattern: "Heap Merge",
  },
  // ── Trees ─────────────────────────────────────────────
  {
    id: 22,
    topic: "Trees",
    difficulty: "Easy",
    title: "Invert Binary Tree",
    question: "Invert a binary tree (mirror it).",
    hint: "Recursively swap left and right children.",
    approach: "For each node, swap its left and right children, then recurse on both subtrees. Base case: null node.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(h)",
    pattern: "DFS Recursion",
  },
  {
    id: 23,
    topic: "Trees",
    difficulty: "Easy",
    title: "Maximum Depth of Binary Tree",
    question: "Find the maximum depth (height) of a binary tree.",
    hint: "Depth = 1 + max(left depth, right depth).",
    approach: "Recurse: return 0 for null nodes, otherwise return 1 + max(depth(left), depth(right)).",
    timeComplexity: "O(n)",
    spaceComplexity: "O(h)",
    pattern: "DFS Recursion",
  },
  {
    id: 24,
    topic: "Trees",
    difficulty: "Medium",
    title: "Binary Tree Level Order Traversal",
    question: "Return the level-order traversal of a binary tree (values grouped by level).",
    hint: "BFS with a queue, process level by level.",
    approach: "Use a queue. For each level, process all nodes in the current queue, collecting their values, and enqueue their children for the next level.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    pattern: "BFS / Level-order",
  },
  {
    id: 25,
    topic: "Trees",
    difficulty: "Medium",
    title: "Validate Binary Search Tree",
    question: "Determine if a binary tree is a valid BST.",
    hint: "Pass valid range (min, max) down the recursion.",
    approach: "Recursively validate each node: it must be within (min, max). For the left child, update max to current value. For the right child, update min to current value.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(h)",
    pattern: "DFS with Constraints",
  },
  {
    id: 26,
    topic: "Trees",
    difficulty: "Medium",
    title: "Lowest Common Ancestor of a BST",
    question: "Find the lowest common ancestor of two nodes in a BST.",
    hint: "Both targets on same side → go deeper; split → found LCA.",
    approach: "Start at root. If both values are smaller, go left. If both are larger, go right. When they split (or one equals root), the current node is the LCA.",
    timeComplexity: "O(h)",
    spaceComplexity: "O(1)",
    pattern: "BST Property",
  },
  {
    id: 27,
    topic: "Trees",
    difficulty: "Hard",
    title: "Binary Tree Maximum Path Sum",
    question: "Find the maximum path sum in a binary tree (path can start and end at any node).",
    hint: "At each node, consider the max 'through' path and max 'extending' path.",
    approach: "DFS returns the max gain extending from each node (node + max(left, right, 0)). At each node, also compute the 'through' sum (left + node + right) and update the global max.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(h)",
    pattern: "DFS with Global State",
  },
  {
    id: 28,
    topic: "Trees",
    difficulty: "Hard",
    title: "Serialize and Deserialize Binary Tree",
    question: "Design an algorithm to serialize and deserialize a binary tree.",
    hint: "Preorder traversal with null markers.",
    approach: "Serialize: preorder DFS, writing values and 'null' for empty nodes. Deserialize: read tokens, recursively build left then right subtrees. A 'null' token returns null.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    pattern: "Preorder + Null Sentinel",
  },
  // ── Tries ─────────────────────────────────────────────
  {
    id: 29,
    topic: "Tries",
    difficulty: "Medium",
    title: "Implement Trie (Prefix Tree)",
    question: "Implement insert, search, and startsWith methods for a Trie.",
    hint: "Each node has a children map and an isEnd flag.",
    approach: "Each TrieNode has a map of children (char → TrieNode) and an isEnd boolean. Insert: walk/create nodes for each char, mark end. Search: walk nodes, check isEnd. StartsWith: walk nodes, return true if path exists.",
    timeComplexity: "O(m) per operation",
    spaceComplexity: "O(n · m)",
    pattern: "Trie Data Structure",
  },
  {
    id: 30,
    topic: "Tries",
    difficulty: "Medium",
    title: "Design Add and Search Words",
    question: "Design a data structure that supports adding words and searching with '.' wildcard.",
    hint: "DFS through trie, branch on '.' to all children.",
    approach: "Build a standard Trie for insert. For search, when you encounter '.', recursively try all children. For regular characters, follow the specific child.",
    timeComplexity: "O(m) insert, O(26^m) worst search",
    spaceComplexity: "O(n · m)",
    pattern: "Trie + DFS Backtracking",
  },
  {
    id: 31,
    topic: "Tries",
    difficulty: "Hard",
    title: "Word Search II",
    question: "Given a board and a list of words, find all words that can be formed by adjacent cells.",
    hint: "Build a trie from words, DFS on the board.",
    approach: "Insert all words into a Trie. For each cell on the board, DFS through the trie. If a trie path matches board characters (with adjacency), add the word to results. Prune visited cells.",
    timeComplexity: "O(m · n · 4^L)",
    spaceComplexity: "O(W · L)",
    pattern: "Trie + Board DFS",
  },
  // ── Heap / Priority Queue ─────────────────────────────
  {
    id: 32,
    topic: "Heap / Priority Queue",
    difficulty: "Medium",
    title: "Kth Largest Element in an Array",
    question: "Find the kth largest element in an unsorted array.",
    hint: "Min-heap of size k, or quickselect.",
    approach: "Maintain a min-heap of size k. For each element, if larger than heap top, replace and heapify. After processing all elements, the heap top is the kth largest.",
    timeComplexity: "O(n log k)",
    spaceComplexity: "O(k)",
    pattern: "Top-K Pattern",
  },
  {
    id: 33,
    topic: "Heap / Priority Queue",
    difficulty: "Hard",
    title: "Find Median from Data Stream",
    question: "Design a data structure that supports addNum and findMedian from a stream.",
    hint: "Two heaps: max-heap for lower half, min-heap for upper half.",
    approach: "Maintain a max-heap (lower half) and min-heap (upper half). Balance sizes after each insert (differ by at most 1). Median is either the top of the larger heap or the average of both tops.",
    timeComplexity: "O(log n) add, O(1) find",
    spaceComplexity: "O(n)",
    pattern: "Two Heaps",
  },
  // ── Backtracking ──────────────────────────────────────
  {
    id: 34,
    topic: "Backtracking",
    difficulty: "Medium",
    title: "Combination Sum",
    question: "Find all unique combinations of candidates that sum to target (elements can be reused).",
    hint: "DFS with remaining target, allow same index.",
    approach: "DFS: at each step, try adding each candidate (starting from current index to avoid duplicates). Subtract from target. If target = 0, save combination. If < 0, backtrack.",
    timeComplexity: "O(n^(T/M))",
    spaceComplexity: "O(T/M)",
    pattern: "DFS Backtracking",
  },
  {
    id: 35,
    topic: "Backtracking",
    difficulty: "Medium",
    title: "Permutations",
    question: "Given a collection of distinct integers, return all possible permutations.",
    hint: "Swap elements into position, recurse on remaining.",
    approach: "For each position, try placing each unused element there. Mark as used, recurse for next position, then unmark (backtrack). When all positions filled, save the permutation.",
    timeComplexity: "O(n · n!)",
    spaceComplexity: "O(n)",
    pattern: "Backtracking with Used Set",
  },
  {
    id: 36,
    topic: "Backtracking",
    difficulty: "Medium",
    title: "Subsets",
    question: "Given a set of distinct integers, return all possible subsets.",
    hint: "Include/exclude each element.",
    approach: "DFS: for each index, choose to include or exclude the element. At each recursive call, add the current subset to results. Continue until past the last index.",
    timeComplexity: "O(n · 2^n)",
    spaceComplexity: "O(n)",
    pattern: "Include/Exclude DFS",
  },
  {
    id: 37,
    topic: "Backtracking",
    difficulty: "Hard",
    title: "N-Queens",
    question: "Place n queens on an n×n chessboard so no two queens attack each other.",
    hint: "Track columns, diagonals, and anti-diagonals.",
    approach: "Place queens row by row. For each row, try each column. Check if the column, diagonal (row-col), and anti-diagonal (row+col) are free. Place queen, recurse, then backtrack.",
    timeComplexity: "O(n!)",
    spaceComplexity: "O(n²)",
    pattern: "Constraint Backtracking",
  },
  // ── Graphs ────────────────────────────────────────────
  {
    id: 38,
    topic: "Graphs",
    difficulty: "Medium",
    title: "Number of Islands",
    question: "Count the number of islands in a 2D grid of '1's (land) and '0's (water).",
    hint: "DFS/BFS from each unvisited land cell.",
    approach: "Iterate through the grid. When you find a '1', increment count and DFS/BFS to mark all connected '1's as visited. Each DFS start represents one island.",
    timeComplexity: "O(m × n)",
    spaceComplexity: "O(m × n)",
    pattern: "Grid DFS/BFS",
  },
  {
    id: 39,
    topic: "Graphs",
    difficulty: "Medium",
    title: "Clone Graph",
    question: "Return a deep copy of a connected undirected graph.",
    hint: "Hash map from original node to clone, BFS/DFS.",
    approach: "Use a hash map to track cloned nodes. BFS/DFS from the starting node. For each node, create its clone and recursively clone its neighbors, using the map to avoid revisiting.",
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V)",
    pattern: "Graph DFS + Memoization",
  },
  {
    id: 40,
    topic: "Graphs",
    difficulty: "Medium",
    title: "Course Schedule",
    question: "Determine if you can finish all courses given prerequisite pairs (cycle detection).",
    hint: "Topological sort or DFS cycle detection.",
    approach: "Build adjacency list. Use DFS with three states: unvisited, in-progress, visited. If you visit an in-progress node, there's a cycle. If all nodes can be visited without cycles, return true.",
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V + E)",
    pattern: "Topological Sort / Cycle Detection",
  },
  {
    id: 41,
    topic: "Graphs",
    difficulty: "Medium",
    title: "Pacific Atlantic Water Flow",
    question: "Find cells that can flow water to both Pacific and Atlantic oceans.",
    hint: "Reverse BFS from each ocean border.",
    approach: "BFS/DFS from all Pacific border cells (mark reachable). BFS/DFS from all Atlantic border cells (mark reachable). The intersection of both sets is the answer.",
    timeComplexity: "O(m × n)",
    spaceComplexity: "O(m × n)",
    pattern: "Multi-source BFS",
  },
  {
    id: 42,
    topic: "Graphs",
    difficulty: "Hard",
    title: "Alien Dictionary",
    question: "Given a sorted dictionary of an alien language, derive the character order.",
    hint: "Build a DAG from adjacent words, then topological sort.",
    approach: "Compare adjacent words to find character ordering edges. Build a directed graph. Topological sort (BFS with indegree or DFS) gives the character order. If a cycle exists, order is invalid.",
    timeComplexity: "O(C) total chars",
    spaceComplexity: "O(U + E)",
    pattern: "Topological Sort",
  },
  // ── Dynamic Programming ───────────────────────────────
  {
    id: 43,
    topic: "Dynamic Programming",
    difficulty: "Easy",
    title: "Climbing Stairs",
    question: "You can climb 1 or 2 steps. How many distinct ways to reach the top of n stairs?",
    hint: "It's Fibonacci: dp[i] = dp[i-1] + dp[i-2].",
    approach: "Base cases: dp[1] = 1, dp[2] = 2. For each step i from 3 to n, dp[i] = dp[i-1] + dp[i-2]. Only need two variables for space optimization.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    pattern: "1D DP (Fibonacci variant)",
  },
  {
    id: 44,
    topic: "Dynamic Programming",
    difficulty: "Medium",
    title: "Coin Change",
    question: "Find the fewest coins needed to make a given amount.",
    hint: "dp[amount] = min over all coins of dp[amount - coin] + 1.",
    approach: "Create dp array of size amount+1, initialized to infinity. dp[0] = 0. For each amount from 1 to target, try each coin: dp[i] = min(dp[i], dp[i - coin] + 1) if i >= coin.",
    timeComplexity: "O(n × amount)",
    spaceComplexity: "O(amount)",
    pattern: "Unbounded Knapsack",
  },
  {
    id: 45,
    topic: "Dynamic Programming",
    difficulty: "Medium",
    title: "Longest Increasing Subsequence",
    question: "Find the length of the longest strictly increasing subsequence.",
    hint: "Binary search on tails array for O(n log n).",
    approach: "Maintain a 'tails' array. For each element, binary search for its position in tails. If it extends the longest subsequence, append it. Otherwise, replace the element at the found position. Length of tails is the answer.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    pattern: "Patience Sorting / Binary Search DP",
  },
  {
    id: 46,
    topic: "Dynamic Programming",
    difficulty: "Medium",
    title: "House Robber",
    question: "Rob houses in a line without robbing two adjacent houses. Maximize total money.",
    hint: "dp[i] = max(dp[i-1], dp[i-2] + nums[i]).",
    approach: "At each house, choose to rob it (add to dp[i-2]) or skip it (take dp[i-1]). Take the max. Only two variables needed.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    pattern: "1D DP (Decision at each step)",
  },
  {
    id: 47,
    topic: "Dynamic Programming",
    difficulty: "Medium",
    title: "Word Break",
    question: "Given a string and a dictionary, determine if the string can be segmented into dictionary words.",
    hint: "dp[i] = true if s[0..i] can be segmented.",
    approach: "dp[0] = true (empty string). For each position i, check all previous positions j: if dp[j] is true and s[j..i] is in the dictionary, set dp[i] = true.",
    timeComplexity: "O(n² × m)",
    spaceComplexity: "O(n)",
    pattern: "1D DP with String Matching",
  },
  {
    id: 48,
    topic: "Dynamic Programming",
    difficulty: "Medium",
    title: "Unique Paths",
    question: "Count paths from top-left to bottom-right of an m×n grid, moving only right or down.",
    hint: "dp[i][j] = dp[i-1][j] + dp[i][j-1].",
    approach: "Each cell can be reached from above or from the left. Initialize first row and column to 1. Fill the rest: dp[i][j] = dp[i-1][j] + dp[i][j-1].",
    timeComplexity: "O(m × n)",
    spaceComplexity: "O(n) with 1D optimization",
    pattern: "2D DP (Grid)",
  },
  {
    id: 49,
    topic: "Dynamic Programming",
    difficulty: "Hard",
    title: "Longest Common Subsequence",
    question: "Find the length of the longest common subsequence of two strings.",
    hint: "2D DP table: match → diagonal + 1, else max(left, up).",
    approach: "Create a 2D table. If characters match, dp[i][j] = dp[i-1][j-1] + 1. Otherwise, dp[i][j] = max(dp[i-1][j], dp[i][j-1]). Bottom-right cell is the answer.",
    timeComplexity: "O(m × n)",
    spaceComplexity: "O(m × n)",
    pattern: "2D DP (Two Strings)",
  },
  {
    id: 50,
    topic: "Dynamic Programming",
    difficulty: "Hard",
    title: "Edit Distance",
    question: "Find the minimum operations (insert, delete, replace) to convert word1 to word2.",
    hint: "2D DP: match → diagonal, else 1 + min(insert, delete, replace).",
    approach: "dp[i][j] = operations to convert word1[0..i] to word2[0..j]. If chars match, dp[i][j] = dp[i-1][j-1]. Else dp[i][j] = 1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1]).",
    timeComplexity: "O(m × n)",
    spaceComplexity: "O(m × n)",
    pattern: "2D DP (Edit Operations)",
  },
  // ── Greedy ────────────────────────────────────────────
  {
    id: 51,
    topic: "Greedy",
    difficulty: "Medium",
    title: "Jump Game",
    question: "Determine if you can reach the last index starting from the first index.",
    hint: "Track the farthest reachable index.",
    approach: "Maintain the farthest index you can reach. For each position, if it's beyond farthest, return false. Update farthest = max(farthest, i + nums[i]). If farthest >= last index, return true.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    pattern: "Greedy Forward Scan",
  },
  {
    id: 52,
    topic: "Greedy",
    difficulty: "Medium",
    title: "Jump Game II",
    question: "Find the minimum number of jumps to reach the last index.",
    hint: "BFS-style: track current end and farthest.",
    approach: "Track the end of the current jump range and the farthest you can reach. When you pass the current end, increment jumps and extend the end to the farthest.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    pattern: "Greedy BFS",
  },
  {
    id: 53,
    topic: "Greedy",
    difficulty: "Medium",
    title: "Gas Station",
    question: "Find the starting gas station index to complete a circular route, or return -1.",
    hint: "If total gas ≥ total cost, a solution exists. Track where tank goes negative.",
    approach: "If total gas < total cost, impossible. Otherwise, iterate and track running surplus. When surplus goes negative, reset start to the next station and reset surplus.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    pattern: "Greedy Reset",
  },
  // ── Intervals ─────────────────────────────────────────
  {
    id: 54,
    topic: "Intervals",
    difficulty: "Medium",
    title: "Merge Intervals",
    question: "Merge all overlapping intervals.",
    hint: "Sort by start, then merge greedily.",
    approach: "Sort intervals by start time. Iterate: if current interval overlaps with the last merged interval, extend the end. Otherwise, add a new interval to the result.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    pattern: "Sort + Merge",
  },
  {
    id: 55,
    topic: "Intervals",
    difficulty: "Medium",
    title: "Insert Interval",
    question: "Insert a new interval into a sorted set of non-overlapping intervals, merging if necessary.",
    hint: "Add all intervals before, merge overlapping, add all intervals after.",
    approach: "Collect all intervals that end before the new one. Merge all intervals that overlap with the new one (update start/end). Collect remaining intervals.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    pattern: "Three-phase Merge",
  },
  {
    id: 56,
    topic: "Intervals",
    difficulty: "Medium",
    title: "Non-overlapping Intervals",
    question: "Find the minimum number of intervals to remove to make the rest non-overlapping.",
    hint: "Sort by end time, greedily keep intervals.",
    approach: "Sort by end time. Greedily keep intervals that don't overlap with the last kept interval. Count removed intervals.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(1)",
    pattern: "Greedy Interval Scheduling",
  },
  // ── Math & Geometry ───────────────────────────────────
  {
    id: 57,
    topic: "Math & Geometry",
    difficulty: "Easy",
    title: "Reverse Integer",
    question: "Reverse digits of a 32-bit signed integer. Return 0 if overflow.",
    hint: "Pop digits with mod, push with multiply.",
    approach: "Repeatedly extract the last digit (x % 10) and build the reversed number (rev * 10 + digit). Check for 32-bit overflow before each step.",
    timeComplexity: "O(log x)",
    spaceComplexity: "O(1)",
    pattern: "Digit Manipulation",
  },
  {
    id: 58,
    topic: "Math & Geometry",
    difficulty: "Medium",
    title: "Rotate Image",
    question: "Rotate an n×n matrix 90 degrees clockwise in-place.",
    hint: "Transpose then reverse each row.",
    approach: "Step 1: Transpose the matrix (swap matrix[i][j] with matrix[j][i]). Step 2: Reverse each row. This achieves a 90° clockwise rotation.",
    timeComplexity: "O(n²)",
    spaceComplexity: "O(1)",
    pattern: "Matrix Manipulation",
  },
  {
    id: 59,
    topic: "Math & Geometry",
    difficulty: "Medium",
    title: "Spiral Matrix",
    question: "Return all elements of an m×n matrix in spiral order.",
    hint: "Track four boundaries: top, bottom, left, right.",
    approach: "Maintain four boundaries. Traverse right along top row, down along right column, left along bottom row, up along left column. Shrink boundaries after each direction. Stop when boundaries cross.",
    timeComplexity: "O(m × n)",
    spaceComplexity: "O(1) extra",
    pattern: "Boundary Simulation",
  },
  {
    id: 60,
    topic: "Math & Geometry",
    difficulty: "Medium",
    title: "Set Matrix Zeroes",
    question: "If an element is 0, set its entire row and column to 0. Do it in-place.",
    hint: "Use first row and first column as markers.",
    approach: "Use the first row/column to mark which rows/columns should be zeroed. First scan to set markers. Then zero cells based on markers. Finally handle the first row/column itself.",
    timeComplexity: "O(m × n)",
    spaceComplexity: "O(1)",
    pattern: "In-place Markers",
  },
  // ── Additional high-frequency problems ────────────────
  {
    id: 61,
    topic: "Arrays & Hashing",
    difficulty: "Easy",
    title: "Valid Anagram",
    question: "Given two strings, determine if one is an anagram of the other.",
    hint: "Count character frequencies.",
    approach: "Count the frequency of each character in both strings using a hash map or array. Compare the counts — they must be identical.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1) for 26 letters",
    pattern: "Frequency Count",
  },
  {
    id: 62,
    topic: "Arrays & Hashing",
    difficulty: "Medium",
    title: "Longest Consecutive Sequence",
    question: "Find the length of the longest consecutive elements sequence in an unsorted array.",
    hint: "Use a set; only start counting from sequence beginnings.",
    approach: "Insert all numbers into a set. For each number, if num-1 is NOT in the set (it's a sequence start), count consecutive numbers forward. Track the max length.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    pattern: "Hash Set + Linear Scan",
  },
  {
    id: 63,
    topic: "Two Pointers",
    difficulty: "Hard",
    title: "Trapping Rain Water",
    question: "Given elevation heights, compute how much rainwater can be trapped.",
    hint: "Two pointers tracking left-max and right-max.",
    approach: "Two pointers from both ends. Track left_max and right_max. Water at each position is min(left_max, right_max) - height. Move the pointer with the smaller max inward.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    pattern: "Two Pointers with Max Tracking",
  },
  {
    id: 64,
    topic: "Sliding Window",
    difficulty: "Medium",
    title: "Longest Repeating Character Replacement",
    question: "Find the length of the longest substring with at most k replacements to make all characters same.",
    hint: "Window size - max frequency ≤ k.",
    approach: "Sliding window tracking character frequencies. The window is valid if (window_size - max_frequency) ≤ k. Expand right, shrink left when invalid. Track max valid window size.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    pattern: "Sliding Window + Frequency",
  },
  {
    id: 65,
    topic: "Sliding Window",
    difficulty: "Medium",
    title: "Permutation in String",
    question: "Check if one string's permutation is a substring of another.",
    hint: "Fixed-size window matching frequency counts.",
    approach: "Count frequencies of the pattern. Slide a window of pattern-length across the text. Maintain a frequency count of the window. If counts match, return true.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    pattern: "Fixed Sliding Window",
  },
  {
    id: 66,
    topic: "Binary Search",
    difficulty: "Medium",
    title: "Find Minimum in Rotated Sorted Array",
    question: "Find the minimum element in a rotated sorted array.",
    hint: "Compare mid with right to determine which side the min is on.",
    approach: "Binary search: if nums[mid] > nums[right], minimum is in the right half (lo = mid + 1). Otherwise, minimum is in the left half including mid (hi = mid).",
    timeComplexity: "O(log n)",
    spaceComplexity: "O(1)",
    pattern: "Modified Binary Search",
  },
  {
    id: 67,
    topic: "Trees",
    difficulty: "Easy",
    title: "Same Tree",
    question: "Check if two binary trees are structurally identical with the same values.",
    hint: "Recurse simultaneously on both trees.",
    approach: "If both null, return true. If one null or values differ, return false. Recursively check left subtrees and right subtrees.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(h)",
    pattern: "Dual DFS",
  },
  {
    id: 68,
    topic: "Trees",
    difficulty: "Easy",
    title: "Subtree of Another Tree",
    question: "Check if tree t is a subtree of tree s.",
    hint: "For each node in s, check if it's the same tree as t.",
    approach: "For each node in s, use the 'same tree' check with t. If any match, return true. Recursively check s.left and s.right.",
    timeComplexity: "O(m × n)",
    spaceComplexity: "O(h)",
    pattern: "DFS + Same Tree",
  },
  {
    id: 69,
    topic: "Trees",
    difficulty: "Medium",
    title: "Kth Smallest Element in a BST",
    question: "Find the kth smallest element in a BST.",
    hint: "In-order traversal visits BST nodes in sorted order.",
    approach: "Perform in-order traversal (left → node → right). Count visited nodes. When count reaches k, return the current node's value.",
    timeComplexity: "O(h + k)",
    spaceComplexity: "O(h)",
    pattern: "In-order Traversal",
  },
  {
    id: 70,
    topic: "Trees",
    difficulty: "Medium",
    title: "Construct Binary Tree from Preorder and Inorder",
    question: "Build a binary tree from its preorder and inorder traversal arrays.",
    hint: "Preorder's first element is root; find it in inorder to split left/right.",
    approach: "First element in preorder is the root. Find it in inorder to determine left and right subtree sizes. Recursively build left and right subtrees from the corresponding slices.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    pattern: "Divide and Conquer",
  },
  {
    id: 71,
    topic: "Graphs",
    difficulty: "Medium",
    title: "Graph Valid Tree",
    question: "Given n nodes and edges, check if they form a valid tree (connected, no cycles).",
    hint: "A tree has exactly n-1 edges and is connected.",
    approach: "Check edge count = n-1. Then BFS/DFS from node 0 to verify all nodes are reachable (connected). If both conditions met, it's a valid tree.",
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V + E)",
    pattern: "Connectivity + Cycle Check",
  },
  {
    id: 72,
    topic: "Graphs",
    difficulty: "Medium",
    title: "Number of Connected Components",
    question: "Find the number of connected components in an undirected graph.",
    hint: "Union-Find or DFS/BFS from each unvisited node.",
    approach: "BFS/DFS from each unvisited node, marking all reachable nodes. Each new BFS/DFS start is a new component. Alternatively, use Union-Find.",
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V + E)",
    pattern: "Connected Components",
  },
  {
    id: 73,
    topic: "Dynamic Programming",
    difficulty: "Medium",
    title: "Decode Ways",
    question: "Count the number of ways to decode a digit string where '1'='A', ..., '26'='Z'.",
    hint: "dp[i] depends on single-digit and two-digit decoding.",
    approach: "dp[i] = (if s[i] is valid single digit, dp[i-1]) + (if s[i-1..i] is valid two-digit 10-26, dp[i-2]). Handle leading zeros.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    pattern: "1D DP (String)",
  },
  {
    id: 74,
    topic: "Dynamic Programming",
    difficulty: "Medium",
    title: "Maximum Product Subarray",
    question: "Find the contiguous subarray with the largest product.",
    hint: "Track both current max and current min (negatives can flip).",
    approach: "At each position, track the maximum and minimum product ending there (a negative times a min can become max). Update global max at each step.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    pattern: "1D DP (Max/Min Tracking)",
  },
  {
    id: 75,
    topic: "Dynamic Programming",
    difficulty: "Medium",
    title: "Longest Palindromic Substring",
    question: "Find the longest palindromic substring in a given string.",
    hint: "Expand around each center (single char and pair).",
    approach: "For each character (and each pair of characters), expand outward while characters match. Track the longest palindrome found. This is simpler and faster than 2D DP.",
    timeComplexity: "O(n²)",
    spaceComplexity: "O(1)",
    pattern: "Expand Around Center",
  },
];
