apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-interview

resources:
  - ../../

patches:
  - path: ingress-aws-alb.yaml
  - path: backend-serviceaccount.yaml
  - path: backend-deployment-aws.yaml
