apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-interview-app-secrets
  namespace: ai-interview
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-secretsmanager
  target:
    name: ai-interview-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: ai-interview-prod/application
        property: JWT_SECRET_KEY
