import { useEffect, useState } from "react";
import PublicNavbar from "@/components/PublicNavbar";
import { apiFetch } from "@/lib/api";

export default function DeveloperPage() {
  const [keys, setKeys] = useState<any[]>([]); const [hooks, setHooks] = useState<any[]>([]); const [name, setName] = useState(""); const [url, setUrl] = useState(""); const [secret, setSecret] = useState(""); const [newKey, setNewKey] = useState(""); const [error, setError] = useState("");
  async function load() { const [k,h] = await Promise.all([apiFetch("/v1/api-keys"), apiFetch("/v1/webhooks")]); if (k.ok) setKeys((await k.json()).items || []); if (h.ok) setHooks((await h.json()).items || []); }
  useEffect(() => { load().catch(() => setError("Sign in to manage developer access.")); }, []);
  async function createKey() { const r = await apiFetch("/v1/api-keys", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) }); const d = await r.json(); if (!r.ok) return setError(d.detail || "Could not create key"); setNewKey(d.key); setName(""); load(); }
  async function createHook() { const r = await apiFetch("/v1/webhooks", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ url, description: "Interview completion events" }) }); const d = await r.json(); if (!r.ok) return setError(d.detail || "Could not create webhook"); setSecret(d.secret); setUrl(""); load(); }
  return <div className="min-h-screen bg-background text-foreground"><PublicNavbar /><main className="mx-auto max-w-5xl px-6 pb-16 pt-32"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-brand">Developer access</p><h1 className="mt-3 text-4xl font-bold tracking-tight md:text-6xl">Connect your interview data.</h1><p className="mt-5 max-w-2xl text-lg leading-7 text-muted-foreground">Create scoped API keys and receive signed interview events in your own systems. Secrets are shown once and stored hashed.</p>{error && <p className="mt-5 text-sm text-destructive">{error}</p>}{newKey && <Secret text={newKey} label="New API key — copy it now" onClose={()=>setNewKey("")} />}{secret && <Secret text={secret} label="Webhook signing secret — copy it now" onClose={()=>setSecret("")} />}<div className="mt-10 grid gap-6 lg:grid-cols-2"><Card title="API keys"><div className="flex gap-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Production integration" className="min-w-0 flex-1 rounded-xl border border-border bg-background px-3 py-2" /><button onClick={createKey} disabled={!name} className="rounded-xl bg-brand px-3 py-2 text-sm font-semibold text-brand-foreground">Create</button></div><div className="mt-5 space-y-3">{keys.map(k=><div key={k.id} className="flex items-center justify-between rounded-xl bg-muted/50 p-3 text-sm"><span><b>{k.name}</b><br /><span className="text-muted-foreground">{k.key_prefix}... · {k.revoked_at ? "Revoked" : "Active"}</span></span>{!k.revoked_at && <button onClick={()=>apiFetch(`/v1/api-keys/${k.id}`,{method:"DELETE"}).then(load)} className="text-destructive">Revoke</button>}</div>)}{!keys.length && <p className="text-sm text-muted-foreground">No API keys yet.</p>}</div></Card><Card title="Webhook endpoints"><div className="flex gap-2"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com/hooks" className="min-w-0 flex-1 rounded-xl border border-border bg-background px-3 py-2" /><button onClick={createHook} disabled={!url} className="rounded-xl bg-brand px-3 py-2 text-sm font-semibold text-brand-foreground">Add</button></div><div className="mt-5 space-y-3">{hooks.map(h=><div key={h.id} className="rounded-xl bg-muted/50 p-3 text-sm"><b>{h.url}</b><br /><span className="text-muted-foreground">Events: interview.completed · {h.active ? "Active" : "Inactive"}</span></div>)}{!hooks.length && <p className="text-sm text-muted-foreground">No webhook endpoints yet.</p>}</div></Card></div></main></div>;
}
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-3xl border border-border bg-card p-6 shadow-sm"><h2 className="mb-5 text-xl font-bold">{title}</h2>{children}</section>; }
function Secret({ text, label, onClose }: { text: string; label: string; onClose: ()=>void }) { return <div className="mt-6 rounded-2xl border border-brand/30 bg-brand/10 p-4"><p className="text-sm font-semibold">{label}</p><code className="mt-2 block break-all rounded-lg bg-background p-3 text-sm">{text}</code><button onClick={onClose} className="mt-3 text-xs font-semibold text-brand">Dismiss</button></div>; }
