import { FormEvent, useEffect, useState } from "react";
import PublicNavbar from "@/components/PublicNavbar";
import { apiFetch } from "@/lib/api";

interface Session { id: string; title: string; mode: string; starts_at: string; duration_minutes: number; timezone: string; status: string; ics_url?: string }

export default function SchedulerPage() {
  const [items, setItems] = useState<Session[]>([]); const [title, setTitle] = useState(""); const [startsAt, setStartsAt] = useState(""); const [mode, setMode] = useState("technical"); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function load() { const res = await apiFetch("/v1/scheduled-sessions"); if (res.ok) setItems((await res.json()).items || []); }
  useEffect(() => { load().catch(() => setError("Sign in to manage your practice schedule.")); }, []);
  async function submit(e: FormEvent) { e.preventDefault(); setLoading(true); setError(""); try { const res = await apiFetch("/v1/scheduled-sessions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, mode, starts_at: new Date(startsAt).toISOString(), duration_minutes: 45, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, reminder_minutes_before: 30 }) }); const data = await res.json(); if (!res.ok) throw new Error(data.detail || "Could not schedule session"); setItems((old) => [data, ...old]); setTitle(""); setStartsAt(""); } catch (err) { setError(err instanceof Error ? err.message : "Could not schedule session"); } finally { setLoading(false); } }
  return <div className="min-h-screen bg-background text-foreground"><PublicNavbar /><main className="mx-auto max-w-5xl px-6 pb-16 pt-32"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-brand">Practice rhythm</p><h1 className="mt-3 text-4xl font-bold tracking-tight md:text-6xl">Put preparation on the calendar.</h1><p className="mt-5 max-w-2xl text-lg leading-7 text-muted-foreground">Schedule focused mock interviews, download calendar invites, and let reminders keep your momentum intact.</p><div className="mt-10 grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><form onSubmit={submit} className="rounded-3xl border border-border bg-card p-6 shadow-sm"><h2 className="text-xl font-bold">Schedule a session</h2><label className="mt-6 block text-sm font-medium">Session title<input required value={title} onChange={e=>setTitle(e.target.value)} className="mt-2 w-full rounded-xl border border-border bg-background px-4 py-3 outline-none focus:border-brand" placeholder="System design warm-up" /></label><label className="mt-5 block text-sm font-medium">Interview type<select value={mode} onChange={e=>setMode(e.target.value)} className="mt-2 w-full rounded-xl border border-border bg-background px-4 py-3 outline-none focus:border-brand"><option value="technical">Technical</option><option value="behavioral">Behavioral</option><option value="coding">Coding</option><option value="system_design">System design</option></select></label><label className="mt-5 block text-sm font-medium">Date and time<input required type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)} className="mt-2 w-full rounded-xl border border-border bg-background px-4 py-3 outline-none focus:border-brand" /></label>{error && <p className="mt-4 text-sm text-destructive">{error}</p>}<button disabled={loading} className="mt-6 w-full rounded-xl bg-brand px-4 py-3 font-semibold text-brand-foreground disabled:opacity-60">{loading ? "Scheduling..." : "Schedule practice"}</button></form><section className="space-y-4">{items.length === 0 ? <div className="rounded-3xl border border-dashed border-border p-8 text-muted-foreground">Your upcoming practice sessions will appear here.</div> : items.map(item => <article key={item.id} className="flex flex-col gap-4 rounded-2xl border border-border bg-card p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm text-muted-foreground">{new Date(item.starts_at).toLocaleString()} · {item.mode.replace("_", " ")}</p><p className="mt-2 text-xs text-muted-foreground">Reminder set for 30 minutes before</p></div><a href={`${import.meta.env.VITE_API_BASE_URL || "http://localhost:8000"}/v1/scheduled-sessions/${item.id}.ics`} className="rounded-xl border border-border px-3 py-2 text-center text-sm font-semibold hover:bg-muted">Download .ics</a></article>)}</section></div></main></div>;
}
