import { FileText, Scale, AlertTriangle, CreditCard, Ban, RefreshCw, Mail } from "lucide-react";
import PublicNavbar from "@/components/PublicNavbar";
import Footer from "@/components/Footer";

const sections = [
  {
    icon: <Scale className="h-5 w-5" />,
    title: "Acceptance of Terms",
    content: [
      "By accessing or using interviewer.ai (the \"Service\"), you agree to be bound by these Terms of Service.",
      "If you are using the Service on behalf of an organization, you represent that you have the authority to bind that organization to these terms.",
      "We reserve the right to update these terms at any time. Continued use of the Service after changes constitutes acceptance of the updated terms.",
      "If you do not agree with any part of these terms, you must discontinue use of the Service immediately.",
    ],
  },
  {
    icon: <FileText className="h-5 w-5" />,
    title: "Use of the Service",
    content: [
      "**Eligibility**: You must be at least 16 years old to use the Service. Users under 18 should have parental or guardian consent.",
      "**Account Security**: You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account.",
      "**Acceptable Use**: You agree to use the Service only for lawful purposes related to interview preparation and professional development.",
      "**Content Ownership**: You retain ownership of all content you upload (resumes, responses). By uploading, you grant us a limited license to process this data for Service functionality.",
      "**AI-Generated Content**: Interview questions, evaluations, and feedback are generated by AI and should be used as supplementary preparation tools, not as guaranteed predictors of interview outcomes.",
    ],
  },
  {
    icon: <CreditCard className="h-5 w-5" />,
    title: "Cost & Access",
    content: [
      "**100% Free**: The Service is provided entirely free of charge. There are no monthly fees, subscription requirements, or payment gateways.",
      "**No Payment Gateways**: We do not collect credit card numbers, billing information, or process payments on the platform.",
      "**Open Source**: The project code is open source and can be self-hosted by individuals and organizations for free under the terms of the repository's open source license.",
    ],
  },
  {
    icon: <Ban className="h-5 w-5" />,
    title: "Prohibited Activities",
    content: [
      "Sharing account credentials with unauthorized users or allowing multiple people to use a single account.",
      "Attempting to reverse-engineer, decompile, or extract the source code of our AI models or proprietary algorithms.",
      "Using automated tools (bots, scrapers) to access the Service or extract data at scale.",
      "Uploading malicious files, content that infringes on third-party intellectual property, or content that violates applicable laws.",
      "Misrepresenting your identity or impersonating another person or entity.",
      "Using the Service to generate content for academic dishonesty or fraudulent purposes.",
    ],
  },
  {
    icon: <AlertTriangle className="h-5 w-5" />,
    title: "Limitation of Liability",
    content: [
      "The Service is provided \"as is\" without warranties of any kind, express or implied, including but not limited to merchantability, fitness for a particular purpose, and non-infringement.",
      "We do not guarantee that the Service will be uninterrupted, error-free, or that AI-generated content will be accurate or suitable for any particular interview.",
      "In no event shall interviewer.ai be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service.",
      "Our total liability for any claim arising from these terms shall not exceed the amount you paid us in the 12 months preceding the claim.",
    ],
  },
  {
    icon: <RefreshCw className="h-5 w-5" />,
    title: "Termination",
    content: [
      "We may suspend or terminate your access to the Service at any time for violation of these terms, with or without prior notice.",
      "Upon termination, your right to use the Service ceases immediately. You may export your data within 30 days of termination.",
      "Sections relating to intellectual property, limitation of liability, and dispute resolution survive termination.",
    ],
  },
  {
    icon: <Mail className="h-5 w-5" />,
    title: "Contact & Dispute Resolution",
    content: [
      "For questions about these terms, contact us at: **legal@interviewer.ai**",
      "Disputes shall be resolved through binding arbitration in accordance with applicable rules, unless you are located in a jurisdiction that prohibits mandatory arbitration.",
      "These Terms are governed by and construed in accordance with the laws of the State of California, United States.",
      "These terms were last updated on April 7, 2026.",
    ],
  },
];

export default function TermsOfService() {
  return (
    <div className="relative min-h-screen bg-background text-foreground">
      <PublicNavbar />

      <div className="pointer-events-none absolute inset-0">
        <div className="absolute left-1/2 top-0 h-[600px] w-[800px] -translate-x-1/2 -translate-y-1/3 rounded-xl bg-accent/10 blur-[140px]" />
      </div>

      <main className="relative mx-auto max-w-4xl px-4 pt-28 pb-20 md:px-6">
        <div className="mb-12 text-center">
          <span className="inline-flex items-center gap-2 rounded-xl border border-primary/25 bg-brand/10 px-4 py-1.5 text-xs font-semibold uppercase tracking-widest text-primary">
            <FileText className="h-3.5 w-3.5" /> Terms of Service
          </span>
          <h1 className="mt-5 text-4xl font-extrabold tracking-tight md:text-5xl">
            Terms of <span className="text-foreground">Service</span>
          </h1>
          <p className="mt-4 text-base leading-relaxed text-muted-foreground md:text-lg">
            Please read these terms carefully before using the interviewer.ai platform.
          </p>
          <p className="mt-2 text-sm text-muted-foreground">Effective date: April 7, 2026</p>
        </div>

        <div className="space-y-6">
          {sections.map((section) => (
            <div key={section.title} className="rounded-2xl border border-border bg-card shadow-sm border border-border p-6 transition-all duration-300 hover:border-primary/20">
              <h2 className="flex items-center gap-3 text-lg font-bold tracking-tight">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand/10 text-primary">
                  {section.icon}
                </div>
                {section.title}
              </h2>
              <ul className="mt-4 space-y-3">
                {section.content.map((item, i) => (
                  <li key={i} className="text-sm leading-relaxed text-muted-foreground pl-1">
                    <span dangerouslySetInnerHTML={{ __html: item.replace(/\*\*(.*?)\*\*/g, '<strong class="text-foreground">$1</strong>') }} />
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </main>

      <Footer />
    </div>
  );
}
